title: Pythonpropertyfileloader
description: A python module to load  property files. Similar to the Properties class in Java.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
